version: '3.5'

services:
  db_server:
    restart: always
    image: f2hex/postgres
    container_name: redmine-db_server
    volumes:
      - ${DATA_PATH}/redmine/db:/var/lib/postgresql/data
    networks:
      - redmine_net

  app_server:
    restart: always
    image: f2hex/redmine
    container_name: redmine-app_server
    volumes:
      - ${DATA_PATH}/redmine/app/files:/usr/src/redmine/files
    networks:
      - redmine_net

  web_server:
    restart: always
    image: f2hex/nginx
    container_name: redmine-web_server
    ports:
      - "443:443"
    volumes:
      - ${DATA_PATH}/redmine/web/log:/var/log/nginx
    networks:
      - redmine_net

networks:
  redmine_net:
    name: redmine
