#!/bin/bash
VOLUME_MOUNT_POINT=$(pwd)/data
APP_NAME=redmine
if [ ! -d $VOLUME_MOUNT_POINT/$APP_NAME/web/log ]; then
  mkdir -p $VOLUME_MOUNT_POINT/$APP_NAME/web/log
fi
if [ ! -d $VOLUME_MOUNT_POINT/$APP_NAME/app/files ]; then
  mkdir -p $VOLUME_MOUNT_POINT/$APP_NAME/app/files
fi
if [ ! -d $VOLUME_MOUNT_POINT/$APP_NAME/db ]; then
  mkdir -p $VOLUME_MOUNT_POINT/$APP_NAME/db
fi
